/**
 * Code Rakshak — Constitutional Filter
 * Ensures the report is professional, constructive, and ethically appropriate.
 */

const BLOCKED_PHRASES = [
    'exploit this vulnerability',
    'use this to hack',
    'attack the system',
    'bypass all security',
    'full exploit code',
];

const SANITIZE_PATTERNS = [
    { pattern: /\b(fuck|shit|damn|crap)\b/gi, replacement: '***' },
];

/**
 * Ensures the report content is professional and constructive.
 */
export function applyConstitutionalFilter(report) {
    if (!report || typeof report !== 'string') {
        return '# Analysis Report\n\nUnable to generate report content.';
    }

    let filtered = report;

    // Apply sanitization patterns
    for (const { pattern, replacement } of SANITIZE_PATTERNS) {
        filtered = filtered.replace(pattern, replacement);
    }

    // Check for blocked phrases and replace with constructive language
    for (const phrase of BLOCKED_PHRASES) {
        if (filtered.toLowerCase().includes(phrase)) {
            filtered = filtered.replace(
                new RegExp(phrase, 'gi'),
                '[vulnerability details omitted for security]'
            );
        }
    }

    // Ensure the report is not empty
    if (filtered.trim().length < 100) {
        filtered += '\n\n*Note: Analysis completed. Please review the findings above and take appropriate action.*';
    }

    // Add Code Rakshak footer if not present
    if (!filtered.includes('Code Rakshak')) {
        filtered += '\n\n---\n*Generated by Code Rakshak — Your Code\'s Guardian*';
    }

    return filtered;
}
